### ISSUE TITLE
Make Tonik/Gin available as plugin

### ISSUE THREAD

**Issue by odil-io** [tonik/gin#11]
I had a very hard time trying to find the Tonik/Gin plugin for the theme.
it would be nice to include the installation instruction of the plugin within the documentation or here on Github as a installable .zip.

The releases tab is a perfect place for, releases. Adding the installable .zip file as resource would aid alot in install time.

tl;dr: suggestion: add a uploadable/installable zip file to releases.

**Comment by jedrzejchalubek** [comment]
Good idea!

We would have to integrate [Github Release API](https://developer.github.com/v3/repos/releases/) as part of the release tagging process.

As far I know we cannot do that via github.com UI. Am I right?

**Comment by odil-io** [comment]
You're really asking me there something. I have zero knowledge or experience with the Github Release API..
But looking at a glance it could be possible to assign a URL to upload the files to the WordPress plugin repository. But I'm not sure.

When I originally made this "issue" I was referring to manually adding a uploadable/installable file to the release post so people like me could just download a ready made zip.

**Comment by odil-io** [comment]
Closing issue as it looks like this project isn't being maintained anymore.
